### ISSUE TITLE
16.2.1 no xml file output after successfully created policy

### ISSUE THREAD

**Issue by atran1981** [MicrosoftDocs/WDAC-Toolkit#27]
after successfully created the policy, no xml output file show. 
![WDAC-issue](https://user-images.githubusercontent.com/79132095/108027869-f398ce00-707e-11eb-8b04-bab76856e7fe.JPG)

**Comment by jgeurten** [comment]
Hi @atran1981, thanks for your patience and filing this issue. Could you please share the log folder as a zip. It would be in the path along the lines of C:\Users\*\AppData\Local\Temp\WDACWizard\Temp\021521_time.

I see you are running the Wizard on a 20H2 64 bit VM, is that correct?

**Comment by KrisLloyd** [comment]
@jgeurten 

Confirmed that this issue is still persistent for a number of different windows versions. Please reopen and investigate.

![WDAC](https://user-images.githubusercontent.com/32377834/130671518-fa5c42c0-5b74-404c-9d0f-fbb6672d2a87.PNG)
![Win10Pro](https://user-images.githubusercontent.com/32377834/130671520-ccfc2ed4-b89f-4e1d-89fc-31aa3f807c3d.PNG)
![WinServer](https://user-images.githubusercontent.com/32377834/130671521-2d9a964c-01bd-4082-b20b-f41207854ac3.PNG)
<img width="464" alt="Screen Shot 2021-08-24 at 2 26 35 PM" src="https://user-images.githubusercontent.com/32377834/130671611-e2fc1d29-17d2-4a0d-bcc1-d186b98684ac.png">

**Comment by jgeurten** [comment]
@KrisLloyd can you please provide me with the log file? I was not able to repro the issue

The file would be in here: C:\Users*\AppData\Local\Temp\WDACWizard\Temp
