### ISSUE TITLE
New Signed and Reputable Mode policies always merge recommended rules

### ISSUE THREAD

**Issue by iainfm** [MicrosoftDocs/WDAC-Toolkit#279]
Hi,

I'm possibly misunderstanding something, but when I create a new Signed and Reputable Mode base policy (either single or multiple), the recommended user and kernel block rules are added to the policy even if they are unticked in the policy creation screen and in settings.

This doesn't seem to happen for Windows or Microsoft Mode policies, and happens with a fresh install of WDAC Wizard (2.3.1.1).

Attached is a sample policy I have made by clicking through the policy creation screens, without selecting the option to merge the recommended rules (renamed to .txt to allow it to be attached).

Best wishes,
Iain
[SignedReputable2023-08-15_test.txt](https://github.com/MicrosoftDocs/WDAC-Toolkit/files/12343997/SignedReputable2023-08-15_test.txt)

**Comment by jgeurten** [comment]
This is sort of by design in the sense that the Signed and Reputable mode template contains all the recommended rules. However, I think that is redundant now that the Wizard supports appending the recommended rules (wasn't always the case). 

I will remove the rules from the Signed and Reputable mode template.
